version: "3.0"
services:
    web:
        image: nginx
        ports:
            - 81:80
    api:
        image: nginx
        ports:
            - 82:80
    database:
        image: mongo
        ports:
            - 27018:27017
    server:
        image: ubuntu