# Generated by Django 3.1.7 on 2021-05-24 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productocarrito',
            name='producto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='cart.product'),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id',)},
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
    ]
